// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousDriveStraight.h"
#include "Commands/JoystickDrive.h"
#include "Commands/RotateInPlace.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    driveJoystick.reset(new Joystick(0));
    
    bButton.reset(new JoystickButton(driveJoystick.get(), 2));
    bButton->WhileHeld(new RotateInPlace(false, 0.25));
    xButton.reset(new JoystickButton(driveJoystick.get(), 3));
    xButton->WhileHeld(new RotateInPlace(true, 0.25));

    // SmartDashboard Buttons
    SmartDashboard::PutData("RotateInPlace: HalfPowerClockwise", new RotateInPlace(false, 0.5));
    SmartDashboard::PutData("RotateInPlace: HalfPowerCounterClockwise", new RotateInPlace(true, 0.5));
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getDriveJoystick() {
   return driveJoystick;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
